---
- name: Ensure podman, podman plugins are installed
  ansible.builtin.dnf:
    name:
      - podman
    state: present

- name: Login to Red Hat Container Registry
  containers.podman.podman_login:
    registry: registry.redhat.io
    username: "{{ podman_registry_username }}"
    password: "{{ podman_registry_password }}"

- name: Create a Podman volume
  containers.podman.podman_volume:
    name: compliance_pgdata
    state: present

- name: Open Firewalld for OPA OT
  ansible.posix.firewalld:
    port: 8181/tcp
    permanent: true
    state: enabled
  notify: Restart Firewalld

- name: Open Firewalld for OPA Compliance
  ansible.posix.firewalld:
    port: 8182/tcp
    permanent: true
    state: enabled
  notify: Restart Firewalld

- name: Open Firewalld for OPA Security
  ansible.posix.firewalld:
    port: 8183/tcp
    permanent: true
    state: enabled
  notify: Restart Firewalld

- name: Open Firewalld for PostgreSQL
  ansible.posix.firewalld:
    port: 5432/tcp
    permanent: true
    state: enabled
  notify: Restart Firewalld

- name: Flush handlers for firewall changes
  ansible.builtin.meta: flush_handlers

- name: Deploy container systemd unit files for OPA
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - "container-opa-ot.service"
    - "container-opa-compliance.service"
    - "container-opa-security.service"
  notify: Reload systemd daemon

- name: Deploy container systemd unit files for postgres
  ansible.builtin.template:
    src: "container-postgresql.service.j2"
    dest: "/etc/systemd/system/container-postgresql.service"
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd daemon

- name: Flush handlers for Systemd changes
  ansible.builtin.meta: flush_handlers

- name: Enable and start container services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - "container-opa-ot.service"
    - "container-opa-compliance.service"
    - "container-opa-security.service"
    - "container-postgresql.service"
